### ISSUE TITLE
Compile in GitHub Actions

### ISSUE THREAD

**Issue by staltz** [nodejs-mobile/nodejs-mobile#121]
As PR #60 laid out, we could build nodejs-mobile in CI, and this would have the benefit of:

- Concurrency
- Not having to manually build on local computers 
  - Thus not having to own one computer for each architecture type
  - Thus not consuming CPU/RAM, allowing other work to be done
- PRs can be automatically checked against compilation errors

------

- [x] Compilation in CI succeeds
- [x] Delete unused artifacts
- [x] Test Android arm64
- [x] Test Android armv7
- [ ] Test Android x64
- [x] Test iOS arm64
- [x] Test iOS Simulator x86_64
- [ ] Test iOS Simulator arm64

**Comment by staltz** [comment]
Runtime error when testing Android (device) arm64:

<details><summary>Details</summary>
<p>

```
08-27 15:29:02.496  3008  3083 E AndroidRuntime: FATAL EXCEPTION: create_react_context
08-27 15:29:02.496  3008  3083 E AndroidRuntime: Process: com.nmrndemo, PID: 3008
08-27 15:29:02.496  3008  3083 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZTVNSt6__ndk119basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE" referenced by "/data/app/~~jc4uPqQ6sqNLo5dCwE7Esg==/com.nmrndemo-3_JeeNc1gPW3RgysGqe5DA==/lib/arm64/libnode.so"...
08-27 15:29:02.496  3008  3083 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
08-27 15:29:02.496  3008  3083 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
08-27 15:29:02.496  3008  3083 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1661)
08-27 15:29:02.496  3008  3083 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.<clinit>(RNNodeJsMobileModule.java:59)
08-27 15:29:02.496  3008  3083 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobilePackage.createNativeModules(RNNodeJsMobilePackage.java:16)
08-27 15:29:02.496  3008  3083 E AndroidRuntime: 	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:43)
08-27 15:29:02.496  3008  3083 E AndroidRuntime: 	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
08-27 15:29:02.496  3008  3083 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1458)
08-27 15:29:02.496  3008  3083 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1429)
08-27 15:29:02.496  3008  3083 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1331)
08-27 15:29:02.496  3008  3083 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.lambda$runCreateReactContextOnNewThread$2(ReactInstanceManager.java:1101)
08-27 15:29:02.496  3008  3083 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.$r8$lambda$AwGS8CysOZmWJw3kRVARHQvw9Ew(Unknown Source:0)
08-27 15:29:02.496  3008  3083 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$$ExternalSyntheticLambda5.run(Unknown Source:4)
08-27 15:29:02.496  3008  3083 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
```

</p>
</details>

**Comment by staltz** [comment]
Apparently CI was using NDK 27 (CI default), not NDK 24 as we were instructing it to. It was a matter of overriding the ANDROID_NDK_HOME env var in CI.

**Comment by staltz** [comment]
Testing on iOS arm64 failed, apparently due to https://github.com/nodejs-mobile/nodejs-mobile/issues/62#issuecomment-1786725205

**Comment by staltz** [comment]
> Testing on iOS arm64 failed, apparently due to [#62 (comment)](https://github.com/nodejs-mobile/nodejs-mobile/issues/62#issuecomment-1786725205)

This was fixed by using macos-13 (Intel) in GHA.

**Comment by staltz** [comment]
Running on simulator failed:

```
Failed to load Info.plist from bundle at path /Users/staltz/Library/Developer/CoreSimulator/Devices/[...]/data/Library/Caches/[...]/nmrndemo.app/Frameworks/NodeMobile.framework

"Couldn't stat Info.plist: No such file or directory"
```

**Comment by staltz** [comment]
I don't have the means to test on Android x64 and iOS Simulator (M1 host machine), so I'll take a risk and assume they are in good shape.
